### ISSUE TITLE
hidden attribute doesn't hide the badge

### ISSUE THREAD

**Issue by LisiLisenok** [PolymerElements/paper-badge#48] opened 2016-05-27 14:22 UTC
at the same time display: 'none' hides the badge.

```html
<link rel="import" href="/bower_components/iron-icons/iron-icons.html">
<link rel="import" href="/bower_components/iron-icons/social-icons.html">
<link rel="import" href="/bower_components/paper-button/paper-button.html">
<link rel="import" href="/bower_components/paper-badge/paper-badge.html">

<dom-module id="badge-test">
  <template>
    <style>
		:host {
			display: block;
		};
	</style>
    
	<paper-button id="withStyle" raised>
		with style
	</paper-button>
	<paper-badge
		icon="social:notifications" for="withStyle" label="+"
		style="display: none; margin-top: 30px"></paper-badge>
    
	<paper-button id="withHidden" raised>
		with hidden
	</paper-button>
	<paper-badge
		icon="social:notifications" for="withHidden" label="+"
		style="margin-top: 30px" hidden=true></paper-badge>	
  </template>
  
  <script>
    
  	Polymer({

      is: 'badge-test',

    });
  </script>
</dom-module>
```

**Comment by notwaldorf** [comment] 2016-05-31 18:57
I can't reproduce this in the shadow or shady dom: http://jsbin.com/wuteya/edit?html,output
(you can change `dom=shadow` to `dom=shady` to enable the shady dom)

**Comment by LisiLisenok** [comment] 2016-05-31 19:28
@notwaldorf 
here is error reproduction code http://jsbin.com/hevogi/edit?html,output
I think issue #46 may be reproduced in the same way.

**Comment by notwaldorf** [comment] 2016-05-31 19:36
Ah. A a temporary workaround, you need to add this style to your dom-module (ideally i think we need to add it to `paper-badge` itself:

```
[hidden] {
  display: none !important;
}
```

**Comment by MartinMoizard** [comment] 2016-06-08 14:48
This can be closed now that https://github.com/PolymerElements/paper-badge/pull/49 is merged.

**Comment by notwaldorf** [comment] 2016-06-23 00:12
Closing as fixed!

**Closed by notwaldorf** 2016-06-23 00:12 UTC
